name: Build Crypto-Provider
on:
  pull_request:
  push:
    branches:
      - main
      - release/**
permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-build-crypto-provider
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Build
        run: make