name: Lint
on:
  pull_request:
  push:
    branches:
      - cp-main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
      - name: Run Linter
        run: make lint