name: Test
on:
  pull_request:
  merge_group:
  push:
    paths:
      - "**.go"
    branches:
      - main
      - release/**

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - uses: actions/checkout@v4

      - name: Run Go Tests
        run: |
          go test -v -race ./... -tags bls12381
